// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY_mchmEP_UJCMCrF5AJl7h0qKCxIYJkk',
    appId: '1:922684130160:web:33bf71a346c89c95a545b5',
    messagingSenderId: '922684130160',
    projectId: 'career-a917b',
    authDomain: 'career-a917b.firebaseapp.com',
    storageBucket: 'career-a917b.firebasestorage.app',
    measurementId: 'G-B3Z59FSPHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrC1-mq_ek_H9xRF_7bOetFCAZoHjsaQo',
    appId: '1:922684130160:android:b30313c1dfab1739a545b5',
    messagingSenderId: '922684130160',
    projectId: 'career-a917b',
    storageBucket: 'career-a917b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDV0hRGYwBkmpZplKpRJLVp0jwItQds_4',
    appId: '1:922684130160:ios:938240ccc28f6e0ba545b5',
    messagingSenderId: '922684130160',
    projectId: 'career-a917b',
    storageBucket: 'career-a917b.firebasestorage.app',
    iosBundleId: 'com.example.careerGuidance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDV0hRGYwBkmpZplKpRJLVp0jwItQds_4',
    appId: '1:922684130160:ios:938240ccc28f6e0ba545b5',
    messagingSenderId: '922684130160',
    projectId: 'career-a917b',
    storageBucket: 'career-a917b.firebasestorage.app',
    iosBundleId: 'com.example.careerGuidance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY_mchmEP_UJCMCrF5AJl7h0qKCxIYJkk',
    appId: '1:922684130160:web:fb4c3936efaaea78a545b5',
    messagingSenderId: '922684130160',
    projectId: 'career-a917b',
    authDomain: 'career-a917b.firebaseapp.com',
    storageBucket: 'career-a917b.firebasestorage.app',
    measurementId: 'G-33ZER2N4SJ',
  );
}
